name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      lc0_branch:
        description: "LeelaChessZero/lc0 branch, tag, or commit SHA"
        required: true
        default: "release/0.32"
      client_branch:
        description: "LeelaChessZero/lczero-client branch"
        required: true
        default: "release"
      lc0_build_opts:
        description: "Lc0 meson flags"
        required: true
        default: "-Dplain_cuda=true -Dnative_cuda=false -Dnative_arch=false -Dopencl=false -Dcudnn=false -Donnx=false"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: leelachesszero/lczero-client

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - { cuda: "12.9.1", ubuntu: "22.04", protobuf: "23", gcc: "",   suffix: "cuda12" }
          - { cuda: "11.5.2", ubuntu: "20.04", protobuf: "17", gcc: "11", suffix: "cuda11" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.suffix }}-latest
          build-args: |
            LC0_BRANCH=${{ inputs.lc0_branch }}
            CLIENT_BRANCH=${{ inputs.client_branch }}
            LC0_BUILD_OPTS=${{ inputs.lc0_build_opts }}
            CUDA_VERSION=${{ matrix.cuda }}
            UBUNTU_VERSION=${{ matrix.ubuntu }}
            LIBPROTOBUF_VERSION=${{ matrix.protobuf }}
            GCC_INSTALL_VERSION=${{ matrix.gcc }}
